# docker-compose.yml - Complete configuration with all services

services:
  # Database Service
  postgres:
    container_name: postgres_container12
    image: postgres
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: user1
      #      POSTGRES_MULTIPLE_DATABASES: medical_auth_db,medical_patient_db,medical_doctor_db,medical_admin_db,medical_payment_db,medical_notification_db
      GDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - medical-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container12
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - medical-network
    restart: unless-stopped

# Volumes for persistent data
volumes:
  postgres_data:
    driver: local
#  prometheus_data:
#    driver: local
#  grafana_data:
#    driver: local

# Networks
networks:
  medical-network:
    driver: bridge