package com.commonlibrary.entity;

public enum NotificationType {
    SYSTEM,
    APPOINTMENT,
    CASE,
    PAYMENT,
    GENERAL,
    VERIFICATION,
    SUBSCRIPTION,
    CONSULTATION,
    WELCOME,
    PASSWORD_RESET,
    DOCTOR_VERIFICATION_REMINDER,
    DOCTOR_STATUS_CHANGE,
    DOCTOR_REGISTRATION,
    NEW_MESSAGE,
    REMINDER,
    CASE_ASSIGNMENT_ESCALATION,
    CASE_ASSIGNMENT_EXPIRED,
    CASE_ASSIGNMENT_REMINDER
}
