package com.commonlibrary.entity;

public enum NotificationType {
    SYSTEM,
    APPOINTMENT,
    CASE,
    PAYMENT,
    GENERAL,
    VERIFICATION,
    SUBSCRIPTION,
    CONSULTATION,
    WELCOME,
    PASSWORD_RESET,
    DOCTOR_VERIFICATION_REMINDER,
    DOCTOR_STATUS_CHANGE,
    DOCTOR_REGISTRATION
}
